### ISSUE TITLE
Push to org

### ISSUE THREAD

**Issue by rodrigondec** [hmanzur/actions-set-secret#1]
# I'm willing to open a PR

I would like to use your action to push a secret to my Organization secrets. And not on my repository.

On this line you set the url to `repo` hard coded.

 https://github.com/hmanzur/actions-set-secret/blob/005a91954f6f378da5736305300a038323893fe6/src/secret.js#L25

# Sugestion
Declare a input to switch this hardcoded value to `org`. It could be a input `org: true` on the action.

This way it could be default false, mantaining the funcionality to the repo.

# Example

```
  repository_or_org:
    description: Repository or organization name
    default: github.repository
    required: false

  org:
    description: flag to push to organization
    default: false
    required: false
```

# Refs
- https://developer.github.com/v3/actions/secrets/#create-or-update-an-organization-secret
