### ISSUE TITLE
Issue with secret value containing dash

### ISSUE THREAD

**Issue by wenqiglantz** [hmanzur/actions-set-secret#18]
Hi, your action works great for secrets with value not containing dash (-), but I noticed that whenever a secret contains dash, your action doesn't persist the secret value when creating a new secret in GitHub.  For example, the following step does create the new repo secret for S3_BUCKET_NAME, however, the value is blank (see verification step below).  

```      
     - name: Create GitHub Repository secret for frontend S3_BUCKET_NAME
        uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: 'S3_BUCKET_NAME'
          value: 'abc-company-bucket'
          repository: ${{ github.repository }}
          token: ${{ secrets.GH_ACTIONS_SECRETS_PAT }}
```

When I tried to verify that newly created secret "abc-company-bucket" using this step below, it retrieved blank value.  But when I modified the secret value from "abc-company-bucket" to "abccompanybucket" in the above step, this step retrieved that value successfully.
```   
     - name: Verify secrets
        run: |
          echo ${{ secrets.S3_BUCKET_NAME }} | sed -e 's/\(.\)/\1 /g'
```

Please help find root cause and provide a fix.  Thanks!
